### ISSUE TITLE
Como finalizar o programa?

### ISSUE THREAD

**Issue by rochacbruno** [karlamagueta/sistema_checkin_hotel#2]
https://github.com/karlamagueta/sistema_checkin_hotel/blob/ae7502c6e924d8ce56a60b7e474c37014d63e7fa/karla_hotel.py#L22

você criou a variavel `programa_aberto` mas não está em nenhum lugar dando a possibilidade para o usuário alterar o estado dela para `False`

**Comment by karlamagueta** [comment]
Resolvido
